# 方式一给类注入属性：类注解上有ServerProperties  @ConfigurationProperties("server")
server:
  port: 8081
# 方式二：给属性注入默认值  @Value("${demo.config.message:默认消息}")
#demo:
#  config:
#    message: 这是 Nacos 配置中心动态刷新的消息！时间戳：{随机数字}
spring:
  application:
    name: provider-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # Nacos 3.x 默认使用 gRPC 端口（9848），无需额外配置
        # 开启自动注册，缺省容易报错
        username: nacos   # 检查这里
        password: nacos    # 检查这里
      config:
        username: nacos   # 检查这里
        password: nacos    # 检查这里
        server-addr: 127.0.0.1:8848   # Nacos 服务端地址
        file-extension: yaml          # 配置文件格式（必须与 Nacos 中创建的一致）
  config:
    import:
      - optional:nacos:provider-service.yaml?refresh=true
#  reactor:
#    context-propagation: auto
management:
  tracing:
    sampling:
      probability: 1.0 # 采样率，1.0 表示 100% 采样，生产环境建议调低，如 0.1
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # 你的 Zipkin 服务器地址