server:
  port: 8083   # 网关端口
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos   # 检查这里
        password: nacos    # 检查这里
    gateway:
        server:
          webflux:
            routes:
              # 路由规则：将 /provider/** 转发到 provider-service
              - id: provider-route
                uri: lb://provider-service   # lb:// 表示负载均衡
                predicates:
                  - Path=/provider/**
                filters:
                  - StripPrefix=1            # 去掉第一个路径段（/provider）
              # 将 /consumer/** 转发到 consumer-service
              - id: consumer-route
                uri: lb://consumer-service
                predicates:
                  - Path=/consumer/**
                filters:
                  - StripPrefix=1
              # 可选：直接转发到 /hello 路径（无需前缀）
              - id: hello-route
                uri: lb://provider-service
                predicates:
                  - Path=/hello
                filters:
                # 不需要 StripPrefix，因为路径无需截断
    sentinel:
      transport:
        dashboard: localhost:8858  # 指向你刚启动的 Sentinel 控制台
        # port: 8719               # 默认8719，如被占用可修改
        eager: true                # 建议开启，让应用启动时立即连接控制台
  reactor:
    context-propagation: auto
management:
  tracing:
    sampling:
      probability: 1.0 # 采样率，1.0 表示 100% 采样，生产环境建议调低，如 0.1
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # 你的 Zipkin 服务器地址
